version: '3'

services:
  goerd:
    image: goerd:develop
    build:
      context: ./
    command: goerd -oy /tmp/schema.yaml -dsn "postgres://postgres:goerd@db:5432/test?sslmode=disable"
    volumes:
      - ./output:/tmp


  db:
    image: postgres:12.5-alpine
    restart: unless-stopped
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: goerd
