version: '3'

services:
  goerd:
    image: goerd:develop
    build:
      context: ./
    command: goerd -from "postgres://postgres:goerd@db:5432/test?sslmode=disable" -to /tmp/schema.yaml
    volumes:
      - ./output:/tmp
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    restart: unless-stopped
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: goerd
      POSTGRES_DB: test
